AutoPrime/Controllers/MantenedorController.cs
using AutoPrime.Datos;
using AutoPrime.Models;
using Microsoft.AspNetCore.Mvc;

namespace AutoPrime.Controllers
{
    public class MantenedorController : Controller
    {
        PersonaDatos _PersonaDatos = new PersonaDatos();
        public IActionResult Listar()
        {
            //La vista mostrará una lista de personas
            var oLista = _PersonaDatos.Listar();
            return View(oLista);
        }

        public IActionResult Guardar()
        {
            //Sólo devuelve la vista
            return View();
        }

        [HttpPost]
        public IActionResult Guardar(PersonaModelo oPersona)
        {
            //Recibe el objeto para guardarlo en la Base de Datos
            if (!ModelState.IsValid)
                return View();

            var respuesta = _PersonaDatos.Guardar(oPersona);
            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }

        public IActionResult Editar(int IdPersona)
        {
            var oPersona = _PersonaDatos.Obtener(IdPersona);
            return View(oPersona);
        }

        [HttpPost]
        public IActionResult Editar(PersonaModelo oPersona)
        {
            if (!ModelState.IsValid)
                return View();


            var respuesta = _PersonaDatos.Editar(oPersona);

            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }

        public IActionResult Eliminar(int IdPersona)
        {
            //METODO SOLO DEVUELVE LA VISTA
            var ocontacto = _PersonaDatos.Obtener(IdPersona);
            return View(ocontacto);
        }

        [HttpPost]
        public IActionResult Eliminar(PersonaModelo oPersona)
        {

            var respuesta = _PersonaDatos.Eliminar(oPersona.IdPersona);

            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }

    }
}

AutoPrime/Views/Mantenedor/Editar.cshtml
@model PersonaModelo
@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Editar Usuario
    </div>
    <div class="card-body">

        <form asp-action="Editar" asp-controller="Mantenedor" method="post">

            <input asp-for="IdPersona" type="hidden" class="form-control">

            <div class="mb-3">
                <label class="form-label">Identificacion</label>
                <input asp-for="Identificacion" type="text" class="form-control">
                <span asp-validation-for="Identificacion" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label class="form-label">Nombre</label>
                <input asp-for="Nombres" type="text" class="form-control">
                <span asp-validation-for="Nombres" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label class="form-label">Apellido</label>
                <input asp-for="Apellidos" type="text" class="form-control">
                <span asp-validation-for="Apellidos" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label class="form-label">Nacimiento</label>
                <input asp-for="FechaNacimiento" type="text" class="form-control">
                <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-primary">Guardar</button>

            <a asp-action="Listar" asp-controller="Mantenedor" class="btn btn-warning">Volver a la lista</a>
        </form>
    </div>
</div>

AutoPrime/Views/Mantenedor/Eliminar.cshtml
@model PersonaModelo
@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Eliminar una Persona
    </div>
    <div class="card-body">


        <form asp-action="Eliminar" asp-controller="Mantenedor" method="post">

            <input asp-for="IdPersona" type="hidden" class="form-control">

            <div class="alert alert-danger" role="alert">
                ¿Desea eliminar la Persona: @Html.DisplayTextFor(m => m.Nombres) ?
            </div>

            <button type="submit" class="btn btn-danger">Elimnar</button>
            <a asp-action="Listar" asp-controller="Mantenedor" class="btn btn-warning">Volver a la lista</a>
        </form>
    </div>
</div>

AutoPrime/Views/Mantenedor/Guardar.cshtml
@model PersonaModelo
@{
    ViewData["Title"] = "Guardar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Crear Persona
    </div>
    <div class="card-body">
        <form asp-action="Guardar" asp-controller="Mantenedor" method="post">
            <div class="mb-3">
                <label class="form-label">Identificación</label>
                <input asp-for="Identificacion" type="text" class="form-control">
                <span asp-validation-for="Identificacion" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Nombres</label>
                <input asp-for="Nombres" type="text" class="form-control">
                <span asp-validation-for="Nombres" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Apellidos</label>
                <input asp-for="Apellidos" type="text" class="form-control">
                <span asp-validation-for="Apellidos" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Fecha de Nacimiento</label>
                <input asp-for="FechaNacimiento" type="date" class="form-control">
                <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">Guardar</button>
            <a asp-action="Listar" asp-controller="Mantenedor" class="btn btn-warning">Volver a la lista</a>
        </form>
    </div>
</div>

AutoPrime/Views/Mantenedor/Listar.cshtml
@model List<PersonaModelo>
@{
    ViewData["Title"] = "Listar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Listado de Personas
    </div>
    <div class="card-body">
        <a asp-action="Guardar" asp-controller="Mantenedor" class="btn btn-success"><i class="bi bi-plus-circle"></i>Crear Nuevo</a>
        <hr />
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Identificacion</th>
                    <th>Nombres</th>
                    <th>Apellidos</th>
                    <th>Fecha de Nacimiento Nacimiento</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Identificacion</td>
                        <td>@item.Nombres</td>
                        <td>@item.Apellidos</td>
                        <td>@item.FechaNacimiento</td>
                        <td>
                            <a asp-action="Editar" asp-controller="Mantenedor" class="btn btn-primary btn-sm" asp-route-IdPersona="@item.IdPersona"><i class="bi bi-pencil-square"></i>Editar</a>
                            <a asp-action="Eliminar" asp-controller="Mantenedor" class="btn btn-danger btn-sm" asp-route-IdPersona="@item.IdPersona"><i class="bi bi-x-octagon"></i>Eliminar</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>