AutoPrime/Controllers/SeguroController.cs
using AutoPrime.Datos;
using AutoPrime.Models;
using Microsoft.AspNetCore.Mvc;

namespace AutoPrime.Controllers
{
    public class SeguroController : Controller
    {
        SeguroDatos _SeguroDatos = new SeguroDatos();
        public IActionResult Listar()
        {
            //La vista mostrará una lista de personas
            var oLista = _SeguroDatos.Listar();
            return View(oLista);
        }

        public IActionResult Guardar()
        {
            //Sólo devuelve la vista
            return View();
        }

        [HttpPost]
        public IActionResult Guardar(SeguroModelo oSeguro)
        {
            //Recibe el objeto para guardarlo en la Base de Datos
            if (!ModelState.IsValid)
                return View();

            var respuesta = _SeguroDatos.Guardar(oSeguro);
            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }

        public IActionResult Editar(int IdSeguro)
        {
            var oSeguro = _SeguroDatos.Obtener(IdSeguro);
            return View(oSeguro);
        }

        [HttpPost]
        public IActionResult Editar(SeguroModelo oSeguro)
        {
            if (!ModelState.IsValid)
                return View();


            var respuesta = _SeguroDatos.Editar(oSeguro);

            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }

        public IActionResult Eliminar(int IdSeguro)
        {
            //METODO SOLO DEVUELVE LA VISTA
            var oSeguro = _SeguroDatos.Obtener(IdSeguro);
            return View(oSeguro);
        }

        [HttpPost]
        public IActionResult Eliminar(SeguroModelo oSeguro)
        {

            var respuesta = _SeguroDatos.Eliminar(oSeguro.IdSeguro);

            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }

    }
}

AutoPrime/Views/Seguro/Editar.cshtml
@model SeguroModelo
@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <title>###AutoPrime### - Tu taller confiable</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="icon" type="image/png" href="~/images/icons/favicon.ico" />
	<link rel="stylesheet" type="text/css" href="~/vendor/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="~/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="~/vendor/animate/animate.css">
	<link rel="stylesheet" type="text/css" href="~/vendor/css-hamburgers/hamburgers.min.css">
	<link rel="stylesheet" type="text/css" href="~/vendor/select2/select2.min.css">
	<link rel="stylesheet" type="text/css" href="~/css/util.css">
	<link rel="stylesheet" type="text/css" href="~/css/main.css">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<img src="~/Images/EditarSeguro.png" alt="AutoPrime">
				</div>

			<form asp-action="Editar" asp-controller="Seguro" method="post">
				<span class="login100-form-title">
						Editar Seguro
					</span>
            <input asp-for="IdSeguro" type="hidden" class="form-control">

            <div class="mb-3">
                <label class="form-label">Fecha de Inicio</label>
						<input asp-for="FechaInicio" type="date" class="input100">
                <span asp-validation-for="FechaInicio" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label class="form-label">Fecha de Fin</label>
						<input asp-for="FechaFinal" type="date" class="input100">
                <span asp-validation-for="FechaFinal" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label class="form-label">Número de Póliza</label>
						<input asp-for="PolizaNumero" type="text" class="input100">
                <span asp-validation-for="PolizaNumero" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label class="form-label">Tipo de Seguro</label>
						<input asp-for="Tipo" type="text" class="input100">
                <span asp-validation-for="Tipo" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-success">Guardar</button>

            <a asp-action="Listar" asp-controller="Seguro" class="btn btn-info">Volver a la lista</a>
        </form>
			</div>
		</div>
	</div>
	
	

	
	<script src="~/vendor/jquery/jquery-3.2.1.min.js"></script>
	<script src="~/vendor/bootstrap/js/popper.js"></script>
	<script src="~/vendor/bootstrap/js/bootstrap.min.js"></script>
	<script src="~/vendor/select2/select2.min.js"></script>
	<script src="~/vendor/tilt/tilt.jquery.min.js"></script>
	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>
	<script src="~/js/main.js"></script>

</body>
</html>

AutoPrime/Views/Seguro/Eliminar.cshtml
@model SeguroModelo
@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Eliminar un Seguro
    </div>
    <div class="card-body">


        <form asp-action="Eliminar" asp-controller="Seguro" method="post">

            <input asp-for="IdSeguro" type="hidden" class="form-control">

            <div class="alert alert-danger" role="alert">
                ¿Desea eliminar el Seguro: @Html.DisplayTextFor(m => m.PolizaNumero) ?
            </div>

            <button type="submit" class="btn btn-danger">Eliminar</button>
            <a asp-action="Listar" asp-controller="Seguro" class="btn btn-warning">Volver a la lista</a>
        </form>
    </div>
</div>

AutoPrime/Views/Seguro/Guardar.cshtml
@model SeguroModelo
@{
	ViewData["Title"] = "Guardar";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
	<title>###AutoPrime### - Tu taller confiable</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="icon" type="image/png" href="~/images/icons/favicon.ico" />
	<link rel="stylesheet" type="text/css" href="~/vendor/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="~/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="~/vendor/animate/animate.css">
	<link rel="stylesheet" type="text/css" href="~/vendor/css-hamburgers/hamburgers.min.css">
	<link rel="stylesheet" type="text/css" href="~/vendor/select2/select2.min.css">
	<link rel="stylesheet" type="text/css" href="~/css/util.css">
	<link rel="stylesheet" type="text/css" href="~/css/main.css">
	<meta name="viewport" content="width=device-width, initial-scale=1" />
</head>
<body>

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<img src="~/Images/GuardarSeguro.jpg" alt="AutoPrime">
				</div>

				<form asp-action="Guardar" asp-controller="Seguro" method="post">
					<span class="login100-form-title">
						Agregar un seguro
					</span>
					<div class="mb-3">
						<label class="form-label">Fecha de Inicio</label>
						<input asp-for="FechaInicio" type="date" class="input100">
						<span asp-validation-for="FechaInicio" class="text-danger"></span>
					</div>
					<div class="mb-3">
						<label class="form-label">Fecha Final</label>
						<input asp-for="FechaFinal" type="date" class="input100">
						<span asp-validation-for="FechaFinal" class="text-danger"></span>
					</div>
					<div class="mb-3">
						<label class="form-label">Número de Póliza</label>
						<input asp-for="PolizaNumero" type="text" class="input100">
						<span asp-validation-for="PolizaNumero" class="text-danger"></span>
					</div>
					<div class="mb-3">
						<label class="form-label">Tipo de Seguro</label>
						<input asp-for="Tipo" type="text" class="input100">
						<span asp-validation-for="Tipo" class="text-danger"></span>
					</div>

					<div class="mb-3">
						<label class="form-label">Propietario</label>
						<input asp-for="FkDueno" type="text" class="input100">
						<span asp-validation-for="FkDueno" class="text-danger"></span>
					</div>
					<button type="submit" class="btn btn-success">Guardar</button>
					<a asp-action="Listar" asp-controller="Seguro" class="btn btn-info">Volver a la lista</a>
				</form>
			</div>
		</div>
	</div>




	<script src="~/vendor/jquery/jquery-3.2.1.min.js"></script>
	<script src="~/vendor/bootstrap/js/popper.js"></script>
	<script src="~/vendor/bootstrap/js/bootstrap.min.js"></script>
	<script src="~/vendor/select2/select2.min.js"></script>
	<script src="~/vendor/tilt/tilt.jquery.min.js"></script>
	<script>
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>
	<script src="~/js/main.js"></script>

</body>
</html>

AutoPrime/Views/Seguro/Listar.cshtml
@model List<SeguroModelo>
@{
    ViewData["Title"] = "Listar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section head{
    <style type="text/css">
        body {
            background-image: url('/images/fondo.png');
            margin: 0;
        }
    </style>
}


    <div class="card">
        <div class="card-header">
            Listado de Seguros
        </div>
        <div class="card-body">
            <a asp-action="Guardar" asp-controller="Seguro" class="btn btn-success"><i class="bi bi-plus-circle"></i>Crear Nuevo</a>
            <hr />
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Fecha de Inicio</th>
                        <th>Fecha de Fin</th>
                        <th>Número de Poliza</th>
                        <th>Tipo</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.FechaInicio</td>
                        <td>@item.FechaFinal</td>
                        <td>@item.PolizaNumero</td>
                        <td>@item.Tipo</td>
                        <td>
                            <a asp-action="Editar" asp-controller="Seguro" class="btn btn-primary btn-sm" asp-route-IdSeguro="@item.IdSeguro"><i class="bi bi-pencil-square"></i>Editar</a>
                            <a asp-action="Eliminar" asp-controller="Seguro" class="btn btn-danger btn-sm" asp-route-IdSeguro="@item.IdSeguro"><i class="bi bi-x-octagon"></i>Eliminar</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>