AutoPrime/Controllers/VehiculoController.cs
using AutoPrime.Datos;
using AutoPrime.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AutoPrime.Controllers
{
    public class VehiculoController : Controller
    {

        VehiculoDatos _VehiculoDatos = new VehiculoDatos();
        public IActionResult Listar()
        {
            //La vista mostrará una lista de personas
            var oLista = _VehiculoDatos.Listar();
            return View(oLista);
        }

        public IActionResult Guardar()
        {
            //Sólo devuelve la vista
            return View();
        }

        [HttpPost]
        public IActionResult Guardar(VehiculoModelo oVehiculo)
        {
            List<SelectListItem> Propietarios = new()
            {
                new SelectListItem { Value = "1", Text = "Victor Quintero" },
                new SelectListItem { Value = "2", Text = "Alejandro Rincón" },
                new SelectListItem { Value = "3", Text = "Carlos Slim" }
            };

            //assigning SelectListItem to view Bag
            ViewBag.Propietarios = Propietarios;

            //Recibe el objeto para guardarlo en la Base de Datos
            if (!ModelState.IsValid)
                return View();

            var respuesta = _VehiculoDatos.Guardar(oVehiculo);
            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }

        public IActionResult Editar(int IdVehiculo)
        {
            var oVehiculo = _VehiculoDatos.Obtener(IdVehiculo);
            return View(oVehiculo);
        }

        [HttpPost]
        public IActionResult Editar(VehiculoModelo oVehiculo)
        {
            if (!ModelState.IsValid)
                return View();


            var respuesta = _VehiculoDatos.Editar(oVehiculo);

            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }

        public IActionResult Eliminar(int IdVehiculo)
        {
            //METODO SOLO DEVUELVE LA VISTA
            var oVehiculo = _VehiculoDatos.Obtener(IdVehiculo);
            return View(oVehiculo);
        }

        [HttpPost]
        public IActionResult Eliminar(VehiculoModelo oVehiculo)
        {

            var respuesta = _VehiculoDatos.Eliminar(oVehiculo.IdVehiculo);

            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }
        [HttpPost]
        public IActionResult Buscar(string Placa)
        {
            //METODO SOLO DEVUELVE LA VISTA
            var oVehiculo = _VehiculoDatos.Buscar(Placa);
            return View(oVehiculo);
        }

        /*
        public IActionResult Buscar(VehiculoModelo oVehiculo)
        {

            var respuesta = _VehiculoDatos.Buscar(oVehiculo.Placa);

            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }*/

    }
}

AutoPrime/Views/Vehiculo/Editar.cshtml
@model VehiculoModelo
@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <title>###AutoPrime### - Tu taller confiable</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="icon" type="image/png" href="~/images/icons/favicon.ico" />
	<link rel="stylesheet" type="text/css" href="~/vendor/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="~/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="~/vendor/animate/animate.css">
	<link rel="stylesheet" type="text/css" href="~/vendor/css-hamburgers/hamburgers.min.css">
	<link rel="stylesheet" type="text/css" href="~/vendor/select2/select2.min.css">
	<link rel="stylesheet" type="text/css" href="~/css/util.css">
	<link rel="stylesheet" type="text/css" href="~/css/main.css">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<img src="~/Images/EditarVehiculo.jpg" alt="AutoPrime">
				</div>

			<form asp-action="Editar" asp-controller="Vehiculo" method="post">
				<span class="login100-form-title">
						Editar Vehiculo
					</span>
            <input asp-for="IdVehiculo" type="hidden" class="form-control">
			<input asp-for="FkDueno" type="hidden" class="form-control">
			<input asp-for="FkSeguro" type="hidden" class="form-control">

            <div class="mb-3">
                <label class="form-label">Placa</label>
						<input asp-for="Placa" type="text" class="input100">
                <span asp-validation-for="Placa" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label class="form-label">Tipo</label>
						<input asp-for="Tipo" type="text" class="input100">
                <span asp-validation-for="Tipo" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label class="form-label">Marca</label>
						<input asp-for="Marca" type="text" class="input100">
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label class="form-label">Modelo</label>
						<input asp-for="Modelo" type="text" class="input100">
                <span asp-validation-for="Modelo" class="text-danger"></span>
            </div>
			<div class="mb-3">
				<label class="form-label">Capacidad</label>
				<input asp-for="Capacidad" type="text" class="input100">
				<span asp-validation-for="Capacidad" class="text-danger"></span>
			</div>
			<div class="mb-3">
				<label class="form-label">Cilindraje</label>
				<input asp-for="Cilindraje" type="text" class="input100">
				<span asp-validation-for="Cilindraje" class="text-danger"></span>
			</div>

			<div class="mb-3">
				<label class="form-label">Ciudad de Origen</label>
				<input asp-for="CiudadOrigen" type="text" class="input100">
				<span asp-validation-for="CiudadOrigen" class="text-danger"></span>
			</div>
			<div class="mb-3">
				<label class="form-label">Descripción</label>
				<input asp-for="Descripcion" type="text" class="input100">
				<span asp-validation-for="Descripcion" class="text-danger"></span>
			</div>
            <button type="submit" class="btn btn-success">Guardar</button>

            <a asp-action="Listar" asp-controller="Vehiculo" class="btn btn-info">Volver a la lista</a>
        </form>
			</div>
		</div>
	</div>
	
	

	
	<script src="~/vendor/jquery/jquery-3.2.1.min.js"></script>
	<script src="~/vendor/bootstrap/js/popper.js"></script>
	<script src="~/vendor/bootstrap/js/bootstrap.min.js"></script>
	<script src="~/vendor/select2/select2.min.js"></script>
	<script src="~/vendor/tilt/tilt.jquery.min.js"></script>
	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>
	<script src="~/js/main.js"></script>

</body>
</html>

AutoPrime/Views/Vehiculo/Eliminar.cshtml
@model VehiculoModelo
@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Eliminar un Vehículo
    </div>
    <div class="card-body">


        <form asp-action="Eliminar" asp-controller="Vehiculo" method="post">

            <input asp-for="IdVehiculo" type="hidden" class="form-control">

            <div class="alert alert-danger" role="alert">
                ¿Desea eliminar el Vehiculo: @Html.DisplayTextFor(m => m.Placa) ?
            </div>

            <button type="submit" class="btn btn-danger">Eliminar</button>
            <a asp-action="Listar" asp-controller="Vehiculo" class="btn btn-warning">Volver a la lista</a>
        </form>
    </div>
</div>

AutoPrime/Views/Vehiculo/Guardar.cshtml
@model VehiculoModelo
@{
	ViewData["Title"] = "Guardar";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
	<title>###AutoPrime### - Tu taller confiable</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="icon" type="image/png" href="~/images/icons/favicon.ico" />
	<link rel="stylesheet" type="text/css" href="~/vendor/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="~/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="~/vendor/animate/animate.css">
	<link rel="stylesheet" type="text/css" href="~/vendor/css-hamburgers/hamburgers.min.css">
	<link rel="stylesheet" type="text/css" href="~/vendor/select2/select2.min.css">
	<link rel="stylesheet" type="text/css" href="~/css/util.css">
	<link rel="stylesheet" type="text/css" href="~/css/main.css">
	<meta name="viewport" content="width=device-width, initial-scale=1" />
</head>
<body>

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<img src="~/Images/GuardarVehiculo.jpg" alt="AutoPrime">
				</div>

				<form asp-action="Guardar" asp-controller="Vehiculo" method="post">
					<span class="login100-form-title">
						Agregar un Vehículo
					</span>
					<div class="mb-3">
						<label class="form-label">Placa</label>
						<input asp-for="Placa" type="text" class="input100">
						<span asp-validation-for="Placa" class="text-danger"></span>
					</div>
					<div class="mb-3">
						<label class="form-label">Tipo</label>
						<input asp-for="Tipo" type="text" class="input100">
						<span asp-validation-for="Tipo" class="text-danger"></span>
					</div>
					<div class="mb-3">
						<label class="form-label">Marca</label>
						<input asp-for="Marca" type="text" class="input100">
						<span asp-validation-for="Marca" class="text-danger"></span>
					</div>
					<div class="mb-3">
						<label class="form-label">Modelo</label>
						<input asp-for="Modelo" type="text" class="input100">
						<span asp-validation-for="Modelo" class="text-danger"></span>
					</div>
					<div class="mb-3">
						<label class="form-label">Capacidad</label>
						<input asp-for="Capacidad" type="text" class="input100">
						<span asp-validation-for="Capacidad" class="text-danger"></span>
					</div>
					<div class="mb-3">
						<label class="form-label">Cilindraje</label>
						<input asp-for="Cilindraje" type="text" class="input100">
						<span asp-validation-for="Cilindraje" class="text-danger"></span>
					</div>
					<div class="mb-3">
						<label class="form-label">Ciudad de Origen</label>
						<input asp-for="CiudadOrigen" type="text" class="input100">
						<span asp-validation-for="CiudadOrigen" class="text-danger"></span>
					</div>
					<div class="mb-3">
						<label class="form-label">Descripción</label>
						<input asp-for="Descripcion" type="text" class="input100">
						<span asp-validation-for="Descripcion" class="text-danger"></span>
					</div>
					<div class="mb-3">
						<label class="form-label">Dueño</label>
						<select class="form-select form-select-sm" id="IdDueno"></select>
						<input asp-for="FkDueno" type="text" class="input100">
						<span asp-validation-for="FkDueno" class="text-danger"></span>
					</div>
					<div class="mb-3">
						<label class="form-label">Seguro</label>
						<select class="form-select form-select-sm" id="IdSeguro"></select>
						<input asp-for="FkSeguro" type="text" class="input100">
						<span asp-validation-for="FkSeguro" class="text-danger"></span>
					</div>
					<button type="submit" class="btn btn-success">Guardar</button>
					<a asp-action="Listar" asp-controller="Vehiculo" class="btn btn-info">Volver a la lista</a>
				</form>
			</div>
		</div>
	</div>






	<script src="~/vendor/jquery/jquery-3.2.1.min.js"></script>
	<script src="~/vendor/bootstrap/js/popper.js"></script>
	<script src="~/vendor/bootstrap/js/bootstrap.min.js"></script>
	<script src="~/vendor/select2/select2.min.js"></script>
	<script src="~/vendor/tilt/tilt.jquery.min.js"></script>
	<script>
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>
	<script src="~/js/main.js"></script>

</body>
</html>

AutoPrime/Views/Vehiculo/Guardar2.cshtml
@model VehiculoModelo
@{
	ViewData["Title"] = "Guardar";
	Layout = "~/Views/Shared/_Layout.cshtml";
	List<SelectListItem> Propietarios = (List<SelectListItem>)ViewBag.Propietarios;
}

<!DOCTYPE html>

<html>
<head>
	<title>###AutoPrime### - Tu taller confiable</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="icon" type="image/png" href="~/images/icons/favicon.ico" />
	<link rel="stylesheet" type="text/css" href="~/vendor/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="~/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="~/vendor/animate/animate.css">
	<link rel="stylesheet" type="text/css" href="~/vendor/css-hamburgers/hamburgers.min.css">
	<link rel="stylesheet" type="text/css" href="~/vendor/select2/select2.min.css">
	<link rel="stylesheet" type="text/css" href="~/css/util.css">
	<link rel="stylesheet" type="text/css" href="~/css/main.css">
	<meta name="viewport" content="width=device-width, initial-scale=1" />
</head>
<body>

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<img src="~/Images/GuardarVehiculo.jpg" alt="AutoPrime">
				</div>

				<form asp-action="Guardar" asp-controller="Vehiculo" method="post">
					<span class="login100-form-title">
						Agregar un Vehículo
					</span>
					<div class="mb-3">
						<label class="form-label">Placa</label>
						<input asp-for="Placa" type="text" class="input100">
						<span asp-validation-for="Placa" class="text-danger"></span>
					</div>
					<div class="mb-3">
						<label class="form-label">Tipo</label>
						<input asp-for="Tipo" type="text" class="input100">
						<span asp-validation-for="Tipo" class="text-danger"></span>
					</div>
					<div class="mb-3">
						<label class="form-label">Marca</label>
						<input asp-for="Marca" type="text" class="input100">
						<span asp-validation-for="Marca" class="text-danger"></span>
					</div>
					<div class="mb-3">
						<label class="form-label">Modelo</label>
						<input asp-for="Modelo" type="text" class="input100">
						<span asp-validation-for="Modelo" class="text-danger"></span>
					</div>
					<div class="mb-3">
						<label class="form-label">Capacidad</label>
						<input asp-for="Capacidad" type="text" class="input100">
						<span asp-validation-for="Capacidad" class="text-danger"></span>
					</div>
					<div class="mb-3">
						<label class="form-label">Cilindraje</label>
						<input asp-for="Cilindraje" type="text" class="input100">
						<span asp-validation-for="Cilindraje" class="text-danger"></span>
					</div>
					<div class="mb-3">
						<label class="form-label">Ciudad de Origen</label>
						<input asp-for="CiudadOrigen" type="text" class="input100">
						<span asp-validation-for="CiudadOrigen" class="text-danger"></span>
					</div>
					<div class="mb-3">
						<label class="form-label">Descripción</label>
						<input asp-for="Descripcion" type="text" class="input100">
						<span asp-validation-for="Descripcion" class="text-danger"></span>
					</div>
					<div class="mb-3">
						<label class="form-label">Dueño</label>
						<select class="form-select form-select-sm" id="IdDueno"></select>
						<input asp-for="FkDueno" type="text" class="input100">
						<span asp-validation-for="FkDueno" class="text-danger"></span>
					</div>
					<div class="mb-3">
						
						<label class="form-label">Seguro</label>
						<select class="form-select form-select-sm" id="IdSeguro"></select>
						<input asp-for="FkSeguro" type="text" class="input100">
						<span asp-validation-for="FkSeguro" class="text-danger"></span>
					</div>
					@using (Html.BeginForm("Select","SelectElements"))
					{
						@Html.DropDownList("Propietarios",null,"{Seleccionar Propietario}",new {@class ="TextBox"})
					}
					<button type="submit" class="btn btn-success">Guardar</button>
					<a asp-action="Listar" asp-controller="Vehiculo" class="btn btn-info">Volver a la lista</a>
				</form>
			</div>
		</div>
	</div>






	<script src="~/vendor/jquery/jquery-3.2.1.min.js"></script>
	<script src="~/vendor/bootstrap/js/popper.js"></script>
	<script src="~/vendor/bootstrap/js/bootstrap.min.js"></script>
	<script src="~/vendor/select2/select2.min.js"></script>
	<script src="~/vendor/tilt/tilt.jquery.min.js"></script>
	<script>
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>
	<script src="~/js/main.js"></script>

</body>
</html>

AutoPrime/Views/Vehiculo/Listar.cshtml
@model List<VehiculoModelo>
@{
    ViewData["Title"] = "Listar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section head{
    <style type="text/css">
        body {
            background-image: url('/images/fondo.png');
            margin: 0;
        }
    </style>
}

    <div class="card">
        <div class="card-header">
            Listado de Propietarios
        </div>
        <div class="card-body">
            <a asp-action="Guardar" asp-controller="Vehiculo" class="btn btn-success"><i class="bi bi-plus-circle"></i>Crear Nuevo</a>
            <hr />
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Placa</th>
                        <th>Tipo</th>
                        <th>Marca</th>
                        <th>Modelo</th>
                        <th>Capacidad</th>
                        <th>Cilindraje</th>
                        <th>Ciudad Origen</th>
                        <th>Descripción</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Placa</td>
                        <td>@item.Tipo</td>
                        <td>@item.Marca</td>
                        <td>@item.Modelo</td>
                        <td>@item.Capacidad</td>
                        <td>@item.Cilindraje</td>
                        <td>@item.CiudadOrigen</td>
                        <td>@item.Descripcion</td>
                        <td>
                            <a asp-action="Editar" asp-controller="Vehiculo" class="btn btn-primary btn-sm" asp-route-IdVehiculo="@item.IdVehiculo"><i class="bi bi-pencil-square"></i>Editar</a>
                            <a asp-action="Eliminar" asp-controller="Vehiculo" class="btn btn-danger btn-sm" asp-route-IdVehiculo="@item.IdVehiculo"><i class="bi bi-x-octagon"></i>Eliminar</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>