AutoPrime/Controllers/EmpleadoAdminController.cs
using AutoPrime.Datos;
using AutoPrime.Models;
using Microsoft.AspNetCore.Mvc;

namespace AutoPrime.Controllers
{
    public class EmpleadoAdminController : Controller
    {
        EmpleadoAdminDatos _EmpleadoAdminDatos = new EmpleadoAdminDatos();
        public IActionResult Listar()
        {
            //La vista mostrará una lista de personas
            var oLista = _EmpleadoAdminDatos.Listar();
            return View(oLista);
        }

        public IActionResult Guardar()
        {
            //Sólo devuelve la vista
            return View();
        }

        [HttpPost]
        public IActionResult Guardar(EmpleadoAdminModelo oEmpleadoAdmin)
        {
            //Recibe el objeto para guardarlo en la Base de Datos
            if (!ModelState.IsValid)
                return View();

            var respuesta = _EmpleadoAdminDatos.Guardar(oEmpleadoAdmin);
            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }

        public IActionResult Editar(int IdAdministrativo)
        {
            var oEmpleadoAdmin = _EmpleadoAdminDatos.Obtener(IdAdministrativo);
            return View(oEmpleadoAdmin);
        }

        [HttpPost]
        public IActionResult Editar(EmpleadoAdminModelo oEmpleadoAdmin)
        {
            if (!ModelState.IsValid)
                return View();


            var respuesta = _EmpleadoAdminDatos.Editar(oEmpleadoAdmin);

            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }

        public IActionResult Eliminar(int IdAdministrativo)
        {
            //METODO SOLO DEVUELVE LA VISTA
            var oEmpleadoAdmin = _EmpleadoAdminDatos.Obtener(IdAdministrativo);
            return View(oEmpleadoAdmin);
        }

        [HttpPost]
        public IActionResult Eliminar(EmpleadoAdminModelo oEmpleadoAdmin)
        {

            var respuesta = _EmpleadoAdminDatos.Eliminar(oEmpleadoAdmin.IdAdministrativo);

            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }

    }
}

AutoPrime/Views/EmpleadoAdmin/Editar.cshtml
@model EmpleadoAdminModelo
@{
	ViewData["Title"] = "Editar";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
	<title>###AutoPrime### - Tu taller confiable</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="icon" type="image/png" href="~/images/icons/favicon.ico" />
	<link rel="stylesheet" type="text/css" href="~/vendor/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="~/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="~/vendor/animate/animate.css">
	<link rel="stylesheet" type="text/css" href="~/vendor/css-hamburgers/hamburgers.min.css">
	<link rel="stylesheet" type="text/css" href="~/vendor/select2/select2.min.css">
	<link rel="stylesheet" type="text/css" href="~/css/util.css">
	<link rel="stylesheet" type="text/css" href="~/css/main.css">
	<meta name="viewport" content="width=device-width, initial-scale=1" />
</head>
<body>

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<img src="~/Images/EditarEmpleadoAdmin.jpg" alt="AutoPrime">
				</div>

				<form asp-action="Editar" asp-controller="EmpleadoAdmin" method="post">
					<span class="login100-form-title">
						Editar Empleado Administrativo
					</span>
					<input asp-for="IdAdministrativo" type="hidden" class="form-control">

					<div class="mb-3">
						<label class="form-label">Identificacion</label>
						<input asp-for="Identificacion" type="text" class="input100">
						<span asp-validation-for="Identificacion" class="text-danger"></span>
					</div>

					<div class="mb-3">
						<label class="form-label">Nombres</label>
						<input asp-for="Nombres" type="text" class="input100">
						<span asp-validation-for="Nombres" class="text-danger"></span>
					</div>

					<div class="mb-3">
						<label class="form-label">Apellidos</label>
						<input asp-for="Apellidos" type="text" class="input100">
						<span asp-validation-for="Apellidos" class="text-danger"></span>
					</div>

					<div class="mb-3">
						<label class="form-label">Nacimiento</label>
						<input asp-for="FechaNacimiento" type="date" class="input100">
						<span asp-validation-for="FechaNacimiento" class="text-danger"></span>
					</div>
					<div class="mb-3">
						<label class="form-label">Teléfono</label>
						<input asp-for="Telefono" type="text" class="input100">
						<span asp-validation-for="Telefono" class="text-danger"></span>
					</div>
					<div class="mb-3">
						<label class="form-label">Nivel de Estudio</label>
						<input asp-for="NivelEstudio" type="text" class="input100">
						<span asp-validation-for="NivelEstudio" class="text-danger"></span>
					</div>
					<div class="mb-3">
						<label class="form-label">Email</label>
						<input asp-for="Email" type="email" class="input100">
						<span asp-validation-for="Email" class="text-danger"></span>
					</div>
					<div class="mb-3">
						<label class="form-label">Cargo</label>
						<input asp-for="Cargo" type="text" class="input100">
						<span asp-validation-for="Cargo" class="text-danger"></span>
					</div>
					<button type="submit" class="btn btn-success">Guardar</button>

					<a asp-action="Listar" asp-controller="EmpleadoAdmin" class="btn btn-info">Volver a la lista</a>
				</form>
			</div>
		</div>
	</div>




	<script src="~/vendor/jquery/jquery-3.2.1.min.js"></script>
	<script src="~/vendor/bootstrap/js/popper.js"></script>
	<script src="~/vendor/bootstrap/js/bootstrap.min.js"></script>
	<script src="~/vendor/select2/select2.min.js"></script>
	<script src="~/vendor/tilt/tilt.jquery.min.js"></script>
	<script>
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>
	<script src="~/js/main.js"></script>

</body>
</html>

AutoPrime/Views/EmpleadoAdmin/Eliminar.cshtml
@model EmpleadoAdminModelo
@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Eliminar un Empleado Administrativo
    </div>
    <div class="card-body">


        <form asp-action="Eliminar" asp-controller="EmpleadoAdmin" method="post">

            <input asp-for="IdAdministrativo" type="hidden" class="form-control">

            <div class="alert alert-danger" role="alert">
                ¿Desea eliminar el Empleado: @Html.DisplayTextFor(m => m.Nombres) ?
            </div>

            <button type="submit" class="btn btn-danger">Eliminar</button>
            <a asp-action="Listar" asp-controller="EmpleadoAdmin" class="btn btn-warning">Volver a la lista</a>
        </form>
    </div>
</div>

AutoPrime/Views/EmpleadoAdmin/Guardar.cshtml
@model EmpleadoAdminModelo
@{
	ViewData["Title"] = "Guardar";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
	<title>###AutoPrime### - Tu taller confiable</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="icon" type="image/png" href="~/images/icons/favicon.ico" />
	<link rel="stylesheet" type="text/css" href="~/vendor/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="~/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="~/vendor/animate/animate.css">
	<link rel="stylesheet" type="text/css" href="~/vendor/css-hamburgers/hamburgers.min.css">
	<link rel="stylesheet" type="text/css" href="~/vendor/select2/select2.min.css">
	<link rel="stylesheet" type="text/css" href="~/css/util.css">
	<link rel="stylesheet" type="text/css" href="~/css/main.css">
	<meta name="viewport" content="width=device-width, initial-scale=1" />
</head>
<body>

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<img src="~/Images/GuardarEmpleadoAdmin.png" alt="AutoPrime">
				</div>

				<form asp-action="Guardar" asp-controller="EmpleadoAdmin" method="post">
					<span class="login100-form-title">
						Agregar un Empleado Administrativo
					</span>
					<div class="mb-3">
						<label class="form-label">Identificación</label>
						<input asp-for="Identificacion" type="text" class="input100">
						<span asp-validation-for="Identificacion" class="text-danger"></span>
					</div>
					<div class="mb-3">
						<label class="form-label">Nombres</label>
						<input asp-for="Nombres" type="text" class="input100">
						<span asp-validation-for="Nombres" class="text-danger"></span>
					</div>
					<div class="mb-3">
						<label class="form-label">Apellidos</label>
						<input asp-for="Apellidos" type="text" class="input100">
						<span asp-validation-for="Apellidos" class="text-danger"></span>
					</div>
					<div class="mb-3">
						<label class="form-label">Fecha de Nacimiento</label>
						<input asp-for="FechaNacimiento" type="date" class="input100">
						<span asp-validation-for="FechaNacimiento" class="text-danger"></span>
					</div>
					<div class="mb-3">
						<label class="form-label">Teléfono</label>
						<input asp-for="Telefono" type="text" class="input100">
						<span asp-validation-for="Telefono" class="text-danger"></span>
					</div>
					<div class="mb-3">
						<label class="form-label">Nivel de Estudio</label>
						<input asp-for="NivelEstudio" type="text" class="input100">
						<span asp-validation-for="NivelEstudio" class="text-danger"></span>
					</div>
					<div class="mb-3">
						<label class="form-label">Email</label>
						<input asp-for="Email" type="email" class="input100">
						<span asp-validation-for="Email" class="text-danger"></span>
					</div>
					<div class="mb-3">
						<label class="form-label">Cargo</label>
						<input asp-for="Cargo" type="text" class="input100">
						<span asp-validation-for="Cargo" class="text-danger"></span>
					</div>
					<button type="submit" class="btn btn-success">Guardar</button>
					<a asp-action="Listar" asp-controller="EmpleadoAdmin" class="btn btn-info">Volver a la lista</a>
				</form>
			</div>
		</div>
	</div>




	<script src="~/vendor/jquery/jquery-3.2.1.min.js"></script>
	<script src="~/vendor/bootstrap/js/popper.js"></script>
	<script src="~/vendor/bootstrap/js/bootstrap.min.js"></script>
	<script src="~/vendor/select2/select2.min.js"></script>
	<script src="~/vendor/tilt/tilt.jquery.min.js"></script>
	<script>
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>
	<script src="~/js/main.js"></script>

</body>
</html>

AutoPrime/Views/EmpleadoAdmin/Listar.cshtml
@model List<EmpleadoAdminModelo>
@{
    ViewData["Title"] = "Listar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section head{
    <style type="text/css">
        body {
            background-image: url('/images/fondo.png');
            margin: 0;
        }
    </style>
}

    <div class="card">
        <div class="card-header">
            Listado de Empleados Administrativos
        </div>
        <div class="card-body">
            <a asp-action="Guardar" asp-controller="EmpleadoAdmin" class="btn btn-success"><i class="bi bi-plus-circle"></i>Crear Nuevo</a>
            <hr />
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Identificacion</th>
                        <th>Nombres</th>
                        <th>Apellidos</th>
                        <th>Fecha de Nacimiento Nacimiento</th>
                        <th>Teléfono</th>
                        <th>Nivel Estudio</th>
                        <th>Email</th>
                        <th>Cargo</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Identificacion</td>
                        <td>@item.Nombres</td>
                        <td>@item.Apellidos</td>
                        <td>@item.FechaNacimiento</td>
                        <td>@item.Telefono</td>
                        <td>@item.NivelEstudio</td>
                        <td>@item.Email</td>
                        <td>@item.Cargo</td>
                        <td>
                            <a asp-action="Editar" asp-controller="EmpleadoAdmin" class="btn btn-primary btn-sm" asp-route-IdAdministrativo="@item.IdAdministrativo"><i class="bi bi-pencil-square"></i>Editar</a>
                            <a asp-action="Eliminar" asp-controller="EmpleadoAdmin" class="btn btn-danger btn-sm" asp-route-IdAdministrativo="@item.IdAdministrativo"><i class="bi bi-x-octagon"></i>Eliminar</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>